import PerspectiveViz from './perspectiveViz'

function AnotherPage() {
  return <PerspectiveViz data={data} />
}

export default AnotherPage

const data = [
  {
    category: 'Technology',
    orderDate: '2023/6/27',
    profit: -57,
    region: 'South',
    sales: 11856,
    state: 'Texas',
    subCategory: 'Tablets',
  },
  {
    category: 'Technology',
    orderDate: '2021/10/9',
    profit: -175,
    region: 'Midwest',
    sales: 1627,
    state: 'Illinois',
    subCategory: 'Phones',
  },
  {
    category: 'Furniture',
    orderDate: '2022/7/12',
    profit: -4114,
    region: 'Midwest',
    sales: 19192,
    state: 'Illinois',
    subCategory: 'Chairs',
  },
  {
    category: 'Office Supplies',
    orderDate: '2022/5/7',
    profit: -1386,
    region: 'Midwest',
    sales: 11727,
    state: 'Illinois',
    subCategory: 'Paper',
  },
  {
    category: 'Technology',
    orderDate: '2023/2/22',
    profit: 507,
    region: 'East',
    sales: 5256,
    state: 'New York',
    subCategory: 'Phones',
  },
  {
    category: 'Apparel',
    orderDate: '2023/6/28',
    profit: -119,
    region: 'West',
    sales: 17006,
    state: 'Washington',
    subCategory: 'Shirts',
  },
  {
    category: 'Office Supplies',
    orderDate: '2021/6/28',
    profit: -2375,
    region: 'West',
    sales: 13272,
    state: 'Washington',
    subCategory: 'Pens',
  },
  {
    category: 'Office Supplies',
    orderDate: '2021/9/12',
    profit: -3725,
    region: 'East',
    sales: 17455,
    state: 'New York',
    subCategory: 'Paper',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2023/3/15',
    profit: -2787,
    region: 'South',
    sales: 18972,
    state: 'Florida',
    subCategory: 'Drinks',
  },
  {
    category: 'Technology',
    orderDate: '2022/11/4',
    profit: 1293,
    region: 'South',
    sales: 10669,
    state: 'Florida',
    subCategory: 'Tablets',
  },
  {
    category: 'Furniture',
    orderDate: '2023/2/26',
    profit: 139,
    region: 'East',
    sales: 1052,
    state: 'Pennsylvania',
    subCategory: 'Desks',
  },
  {
    category: 'Technology',
    orderDate: '2021/10/14',
    profit: 2221,
    region: 'Midwest',
    sales: 17226,
    state: 'Illinois',
    subCategory: 'Tablets',
  },
  {
    category: 'Technology',
    orderDate: '2022/12/13',
    profit: -136,
    region: 'East',
    sales: 13339,
    state: 'New York',
    subCategory: 'Phones',
  },
  {
    category: 'Technology',
    orderDate: '2021/10/27',
    profit: -1550,
    region: 'Midwest',
    sales: 11539,
    state: 'Illinois',
    subCategory: 'Phones',
  },
  {
    category: 'Furniture',
    orderDate: '2023/9/9',
    profit: 1946,
    region: 'Midwest',
    sales: 9377,
    state: 'Illinois',
    subCategory: 'Desks',
  },
  {
    category: 'Apparel',
    orderDate: '2021/3/12',
    profit: 520,
    region: 'East',
    sales: 20259,
    state: 'Pennsylvania',
    subCategory: 'Pants',
  },
  {
    category: 'Apparel',
    orderDate: '2023/3/18',
    profit: 1742,
    region: 'West',
    sales: 19869,
    state: 'Washington',
    subCategory: 'Shoes',
  },
  {
    category: 'Office Supplies',
    orderDate: '2023/11/3',
    profit: 801,
    region: 'Midwest',
    sales: 3935,
    state: 'Illinois',
    subCategory: 'Paper',
  },
  {
    category: 'Furniture',
    orderDate: '2023/12/19',
    profit: -728,
    region: 'Midwest',
    sales: 19267,
    state: 'Illinois',
    subCategory: 'Chairs',
  },
  {
    category: 'Technology',
    orderDate: '2022/2/8',
    profit: -2099,
    region: 'Midwest',
    sales: 11714,
    state: 'Illinois',
    subCategory: 'Computers',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2021/12/6',
    profit: 732,
    region: 'West',
    sales: 9680,
    state: 'Washington',
    subCategory: 'Drinks',
  },
  {
    category: 'Technology',
    orderDate: '2021/9/14',
    profit: -270,
    region: 'East',
    sales: 14642,
    state: 'New York',
    subCategory: 'Tablets',
  },
  {
    category: 'Technology',
    orderDate: '2023/4/11',
    profit: 2971,
    region: 'West',
    sales: 11827,
    state: 'California',
    subCategory: 'Tablets',
  },
  {
    category: 'Technology',
    orderDate: '2023/6/25',
    profit: 250,
    region: 'Midwest',
    sales: 1884,
    state: 'Illinois',
    subCategory: 'Tablets',
  },
  {
    category: 'Technology',
    orderDate: '2021/6/21',
    profit: 443,
    region: 'West',
    sales: 8507,
    state: 'Washington',
    subCategory: 'Phones',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2021/4/23',
    profit: -1723,
    region: 'East',
    sales: 19989,
    state: 'New York',
    subCategory: 'Drinks',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2023/2/18',
    profit: 99,
    region: 'East',
    sales: 7455,
    state: 'Pennsylvania',
    subCategory: 'Drinks',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2021/5/14',
    profit: -5875,
    region: 'South',
    sales: 19898,
    state: 'Texas',
    subCategory: 'Snacks',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2023/2/4',
    profit: -4484,
    region: 'West',
    sales: 14427,
    state: 'California',
    subCategory: 'Candy',
  },
  {
    category: 'Furniture',
    orderDate: '2023/1/28',
    profit: -3668,
    region: 'South',
    sales: 13619,
    state: 'Florida',
    subCategory: 'Chairs',
  },
  {
    category: 'Technology',
    orderDate: '2021/4/12',
    profit: -342,
    region: 'Midwest',
    sales: 1295,
    state: 'Illinois',
    subCategory: 'Phones',
  },
  {
    category: 'Technology',
    orderDate: '2021/12/27',
    profit: 602,
    region: 'Midwest',
    sales: 9310,
    state: 'Illinois',
    subCategory: 'Computers',
  },
  {
    category: 'Apparel',
    orderDate: '2023/10/17',
    profit: -1172,
    region: 'West',
    sales: 15149,
    state: 'California',
    subCategory: 'Shirts',
  },
  {
    category: 'Technology',
    orderDate: '2023/12/21',
    profit: 189,
    region: 'West',
    sales: 6093,
    state: 'Washington',
    subCategory: 'Phones',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2023/12/1',
    profit: 336,
    region: 'South',
    sales: 1206,
    state: 'Florida',
    subCategory: 'Candy',
  },
  {
    category: 'Office Supplies',
    orderDate: '2022/10/24',
    profit: 4018,
    region: 'Midwest',
    sales: 16369,
    state: 'Illinois',
    subCategory: 'Binders',
  },
  {
    category: 'Apparel',
    orderDate: '2021/2/28',
    profit: 1973,
    region: 'East',
    sales: 10566,
    state: 'Pennsylvania',
    subCategory: 'Pants',
  },
  {
    category: 'Office Supplies',
    orderDate: '2022/7/5',
    profit: -748,
    region: 'South',
    sales: 7150,
    state: 'Florida',
    subCategory: 'Binders',
  },
  {
    category: 'Furniture',
    orderDate: '2023/3/26',
    profit: 3705,
    region: 'South',
    sales: 17047,
    state: 'Florida',
    subCategory: 'Desks',
  },
  {
    category: 'Apparel',
    orderDate: '2023/4/16',
    profit: -3480,
    region: 'South',
    sales: 9898,
    state: 'Texas',
    subCategory: 'Pants',
  },
  {
    category: 'Apparel',
    orderDate: '2022/12/27',
    profit: -523,
    region: 'West',
    sales: 10445,
    state: 'California',
    subCategory: 'Shirts',
  },
  {
    category: 'Technology',
    orderDate: '2022/12/10',
    profit: 4428,
    region: 'Midwest',
    sales: 14997,
    state: 'Illinois',
    subCategory: 'Phones',
  },
  {
    category: 'Office Supplies',
    orderDate: '2021/1/19',
    profit: -7227,
    region: 'South',
    sales: 20472,
    state: 'Texas',
    subCategory: 'Binders',
  },
  {
    category: 'Technology',
    orderDate: '2021/1/1',
    profit: 62,
    region: 'East',
    sales: 3356,
    state: 'Pennsylvania',
    subCategory: 'Phones',
  },
  {
    category: 'Technology',
    orderDate: '2022/1/1',
    profit: 4759,
    region: 'East',
    sales: 20362,
    state: 'Pennsylvania',
    subCategory: 'Computers',
  },
  {
    category: 'Furniture',
    orderDate: '2021/8/28',
    profit: 3438,
    region: 'West',
    sales: 13803,
    state: 'Washington',
    subCategory: 'Desks',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2023/12/20',
    profit: -4080,
    region: 'East',
    sales: 10441,
    state: 'Pennsylvania',
    subCategory: 'Candy',
  },
  {
    category: 'Technology',
    orderDate: '2022/11/9',
    profit: -4841,
    region: 'West',
    sales: 12764,
    state: 'California',
    subCategory: 'Tablets',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2021/3/28',
    profit: -617,
    region: 'Midwest',
    sales: 19732,
    state: 'Illinois',
    subCategory: 'Snacks',
  },
  {
    category: 'Apparel',
    orderDate: '2023/8/7',
    profit: -3272,
    region: 'East',
    sales: 8656,
    state: 'Pennsylvania',
    subCategory: 'Pants',
  },
  {
    category: 'Apparel',
    orderDate: '2022/4/4',
    profit: -1354,
    region: 'West',
    sales: 14768,
    state: 'California',
    subCategory: 'Pants',
  },
  {
    category: 'Apparel',
    orderDate: '2022/9/9',
    profit: -1297,
    region: 'Midwest',
    sales: 16614,
    state: 'Illinois',
    subCategory: 'Pants',
  },
  {
    category: 'Apparel',
    orderDate: '2023/9/19',
    profit: -3254,
    region: 'South',
    sales: 11650,
    state: 'Texas',
    subCategory: 'Shoes',
  },
  {
    category: 'Food and Beverage',
    orderDate: '2023/8/4',
    profit: 1761,
    region: 'East',
    sales: 6092,
    state: 'New York',
    subCategory: 'Snacks',
  },
  {
    category: 'Furniture',
    orderDate: '2021/12/16',
    profit: 2238,
    region: 'Midwest',
    sales: 18736,
    state: 'Illinois',
    subCategory: 'Tables',
  },
  {
    category: 'Office Supplies',
    orderDate: '2021/2/11',
    profit: 514,
    region: 'Midwest',
    sales: 11120,
    state: 'Illinois',
    subCategory: 'Binders',
  },
  {
    category: 'Furniture',
    orderDate: '2022/11/16',
    profit: 2300,
    region: 'West',
    sales: 14667,
    state: 'Washington',
    subCategory: 'Tables',
  },
]
